force-app/main/default/objects/Tilewall_Config__c/Tilewall_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Tilewall Config</label>
</CustomObject>

force-app/main/default/objects/Tilewall_Config__c/fields/allowSearch__c.field-meta.xml
<CustomField>
    <fullName>allowSearch__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Adds a search box to the header of the component to enable free-text search of the records. Uses SOSL search which searches most fields, including those not displayed in the tile.</inlineHelpText>
    <label>Allow Search</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/backgroundColor__c.field-meta.xml
<CustomField>
    <fullName>backgroundColor__c</fullName>
    <defaultValue>&apos;#FFFFFF&apos;</defaultValue>
    <inlineHelpText>Background color for the overall Tile Wall component</inlineHelpText>
    <label>Tile Wall Background Color</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/color__c.field-meta.xml
<CustomField>
    <fullName>color__c</fullName>
    <defaultValue>&apos;#FFFFFF&apos;</defaultValue>
    <inlineHelpText>Background color for each individual tile.  6-character HEX format (eg #FFFFFF) MUST be used if opacity is specified.</inlineHelpText>
    <label>Tile Background Color</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/colorFieldName__c.field-meta.xml
<CustomField>
    <fullName>colorFieldName__c</fullName>
    <inlineHelpText>API Name of a record field that provides the background color for the tile, eg. through a formula.  6-char HEX format (eg #FFFFFF) MUST be used by this field if opacity is specified.</inlineHelpText>
    <label>Tile Background Color Fieldname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/columnsLarge__c.field-meta.xml
<CustomField>
    <fullName>columnsLarge__c</fullName>
    <defaultValue>4</defaultValue>
    <label>Tiles per Row (Desktop)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/columnsMedium__c.field-meta.xml
<CustomField>
    <fullName>columnsMedium__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Tiles per Row (Tablet)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/columnsSmall__c.field-meta.xml
<CustomField>
    <fullName>columnsSmall__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Tiles per Row (Mobile)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/displayCount__c.field-meta.xml
<CustomField>
    <fullName>displayCount__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Display the record count in brackets in the component header.</inlineHelpText>
    <label>Display Record Count</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/fieldStyle__c.field-meta.xml
<CustomField>
    <fullName>fieldStyle__c</fullName>
    <defaultValue>&apos;horizontal&apos;</defaultValue>
    <inlineHelpText>Options: horizontal,stacked</inlineHelpText>
    <label>Field Style</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/fixedHeight__c.field-meta.xml
<CustomField>
    <fullName>fixedHeight__c</fullName>
    <inlineHelpText>Fixed Height in pixels (px) or percent (%).  Enter the number and the unit - eg 200px or 10%</inlineHelpText>
    <label>Fixed Height</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/heightOption__c.field-meta.xml
<CustomField>
    <fullName>heightOption__c</fullName>
    <defaultValue>&apos;max-row&apos;</defaultValue>
    <inlineHelpText>Options: max-row,fixed,individual.  Max-Row: Tile auto-size height to fit contents, each tile in a row will be the same height; Fixed: Fixed at specified height; Individual: Each tile sized to fit content.</inlineHelpText>
    <label>Tile Height</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/iconName__c.field-meta.xml
<CustomField>
    <fullName>iconName__c</fullName>
    <inlineHelpText>(Optional) Enter the icon name to appear in the header, eg. standard:account or utility:event. Google &apos;slds icons&apos; to see them all.</inlineHelpText>
    <label>Icon Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/iconSize__c.field-meta.xml
<CustomField>
    <fullName>iconSize__c</fullName>
    <defaultValue>&quot;small&quot;</defaultValue>
    <inlineHelpText>Size for the Title Icon.</inlineHelpText>
    <label>Icon Size</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/imageFieldName__c.field-meta.xml
<CustomField>
    <fullName>imageFieldName__c</fullName>
    <inlineHelpText>API Name of a record field that provides the URL for that tile&apos;s background, eg. through a formula field. Make sure the site hosting the image is added to CSP Trusted Sites if this component is used in Experience Cloud.</inlineHelpText>
    <label>Tile Background Image Fieldname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/imageURL__c.field-meta.xml
<CustomField>
    <fullName>imageURL__c</fullName>
    <inlineHelpText>URL for a default image to be used as each tile&apos;s background. If the Tile Wall is being displayed in Experience Cloud, make sure the site hosting the image is included as a CSP trusted site.</inlineHelpText>
    <label>Tile Background Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/limitResults__c.field-meta.xml
<CustomField>
    <fullName>limitResults__c</fullName>
    <defaultValue>12</defaultValue>
    <inlineHelpText>Controls how many records will be displayed on each page</inlineHelpText>
    <label>Limit Displayed Records</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/media__c.field-meta.xml
<CustomField>
    <fullName>media__c</fullName>
    <inlineHelpText>Icon Name (eg. standard:product) OR Image Url</inlineHelpText>
    <label>Media</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/mediaFieldname__c.field-meta.xml
<CustomField>
    <fullName>mediaFieldname__c</fullName>
    <label>Media Fieldname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/mediaFormat__c.field-meta.xml
<CustomField>
    <fullName>mediaFormat__c</fullName>
    <defaultValue>&apos;default&apos;</defaultValue>
    <inlineHelpText>Options: default, circle</inlineHelpText>
    <label>Media Format</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/noResultsText__c.field-meta.xml
<CustomField>
    <fullName>noResultsText__c</fullName>
    <defaultValue>&apos;No results found, try searching for something else.&apos;</defaultValue>
    <inlineHelpText>Text to display if no results are found after searching</inlineHelpText>
    <label>No Search Results Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/opacity__c.field-meta.xml
<CustomField>
    <fullName>opacity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Opacity of the tiles between 0.0 ((fully transparent) and 1.0 opaque). 6-char HEX color values (eg. #FFFFFF) must be used if opacity is set. Opacity doesn&apos;t work on iOS, tiles will fallback to default background color (no background image).</inlineHelpText>
    <label>Tile Background Opacity</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/orderBy__c.field-meta.xml
<CustomField>
    <fullName>orderBy__c</fullName>
    <inlineHelpText>Use SOQL Syntax for advanced ordering eg. &apos;Name ASC, CloseDate DESC&apos;</inlineHelpText>
    <label>Order By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/orderByDirection__c.field-meta.xml
<CustomField>
    <fullName>orderByDirection__c</fullName>
    <defaultValue>&apos;ASC&apos;</defaultValue>
    <inlineHelpText>ASC, DESC</inlineHelpText>
    <label>Order By Direction</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/orderByFieldname__c.field-meta.xml
<CustomField>
    <fullName>orderByFieldname__c</fullName>
    <label>Order By Fieldname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/padding__c.field-meta.xml
<CustomField>
    <fullName>padding__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Applies padding to the left and right of each field and label.  In horizontal mode, a small amount of padding will be applied to the right of the label if unchecked, to enable separation.</inlineHelpText>
    <label>Field Padding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/searchLabel__c.field-meta.xml
<CustomField>
    <fullName>searchLabel__c</fullName>
    <defaultValue>&apos;Search&apos;</defaultValue>
    <inlineHelpText>Label for the search box, if displayed.</inlineHelpText>
    <label>Search Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/showMedia__c.field-meta.xml
<CustomField>
    <fullName>showMedia__c</fullName>
    <inlineHelpText>Options: icon, image, none</inlineHelpText>
    <label>Show Media</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/size__c.field-meta.xml
<CustomField>
    <fullName>size__c</fullName>
    <defaultValue>&apos;cover&apos;</defaultValue>
    <inlineHelpText>Google &apos;css background-size&apos; for details of each option. Options: auto,length,cover,contain,initial,inherit.</inlineHelpText>
    <label>Tile Background Image Size</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <inlineHelpText>Title for the header of the tile wall component (as opposed to an individual tile)</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/titleAlign__c.field-meta.xml
<CustomField>
    <fullName>titleAlign__c</fullName>
    <defaultValue>&apos;left&apos;</defaultValue>
    <inlineHelpText>Title Alignment. Options: left,center,right</inlineHelpText>
    <label>Title Alignment</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/titleName__c.field-meta.xml
<CustomField>
    <fullName>titleName__c</fullName>
    <label>Title API Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/titleSize__c.field-meta.xml
<CustomField>
    <fullName>titleSize__c</fullName>
    <defaultValue>&apos;body_regular&apos;</defaultValue>
    <inlineHelpText>Text size style for the title (google &apos;slds text&apos; for examples of each style). Options: body_regular,body_small,heading_large,heading_medium,heading_small</inlineHelpText>
    <label>Title Size</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/titleTextCase__c.field-meta.xml
<CustomField>
    <fullName>titleTextCase__c</fullName>
    <defaultValue>&apos;default&apos;</defaultValue>
    <inlineHelpText>Title Case Display. Options: default,lowercase,uppercase</inlineHelpText>
    <label>Title Text Case</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/useAdvancedOrdering__c.field-meta.xml
<CustomField>
    <fullName>useAdvancedOrdering__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Advanced Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/Tilewall_Field__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Tilewall Field</label>
</CustomObject>

force-app/main/default/objects/Tilewall_Field__c/fields/align__c.field-meta.xml
<CustomField>
    <fullName>align__c</fullName>
    <defaultValue>&apos;left&apos;</defaultValue>
    <inlineHelpText>Field Alignment. Options: left,center,right</inlineHelpText>
    <label>Alignment</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/fields/color__c.field-meta.xml
<CustomField>
    <fullName>color__c</fullName>
    <label>Text Color</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/fields/colorFieldname__c.field-meta.xml
<CustomField>
    <fullName>colorFieldname__c</fullName>
    <label>Text Color Fieldname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/fields/label__c.field-meta.xml
<CustomField>
    <fullName>label__c</fullName>
    <inlineHelpText>Optional label for this field.  If omitted, the value will take up the full space.</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/fields/size__c.field-meta.xml
<CustomField>
    <fullName>size__c</fullName>
    <defaultValue>&apos;body_regular&apos;</defaultValue>
    <inlineHelpText>Text size style (google &apos;slds text&apos; for examples of each style). Options: body_regular,body_small,heading_large,heading_medium,heading_small</inlineHelpText>
    <label>Size</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/fields/textCase__c.field-meta.xml
<CustomField>
    <fullName>textCase__c</fullName>
    <defaultValue>&apos;default&apos;</defaultValue>
    <inlineHelpText>Options:default,uppercase,lowercase</inlineHelpText>
    <label>Text Case</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TilewallController_Dynacat.cls
/*
 * Controller class for the Tilewall LWC (Dynacat edition), a much-updated LWC version of an old aura-
 * based demo component I built a few years ago. 
 *
 * The Tile Wall adds more configurable display options for the filtered records. In the config for the component 
 * you can set which fields should be displayed, how they should be aligned, background colours, images, etc. You can
 * also use a formula field on the record to specify a background colour, background image, or a badge foreground/background
 * colour.  And, SOSL search is built in, which enables full-text searching of all SOSL enabled fields on the records.
 *
 * DISCLAIMER: This is sample code only released under the CC0.
 * It is not of production quality, and is not warranted for quality or fitness 
 * for purpose by me or my employer.
*/

public class TilewallController_Dynacat {
    
    @AuraEnabled(cacheable=true)
    public static String getTileWallConfig(String configName) {

        System.debug('Getting Configs Records');
               
        List<String> baseFields = new List<String>{ 
                'title__c',
                'iconName__c',
                'iconSize__c',
                'displayCount__c', 
                'allowSearch__c', 
                'searchLabel__c', 
                'noResultsText__c', 
                'orderBy__c',
                'orderByFieldname__c',
                'orderByDirection__c',
                'useAdvancedOrdering__c',
                'limitResults__c', 
                'columnsLarge__c', 
                'columnsMedium__c', 
                'columnsSmall__c', 
                'backgroundColor__c', 
                'color__c', 
                'colorFieldName__c', 
                'imageURL__c', 
                'imageFieldName__c', 
                'opacity__c', 
                'size__c', 
                'heightOption__c', 
                'fixedHeight__c',
                'titleName__c',
                'titleSize__c',
                'titleTextCase__c',
                'titleAlign__c',
                'fieldStyle__c',
                'padding__c',
                'showMedia__c',
                'media__c',
                'mediaFieldname__c',
                'mediaFormat__c',
                'mediaSize__c'
        };
            
        List<String> configFields = new List<String>();
        configFields.addAll(baseFields);
        
        List<Tilewall_Config__c> twc = Database.query('SELECT Id, Name, ' + String.join(configFields,',') + ' FROM Tilewall_Config__c WHERE Name=\''+configName+'\'');
        
        if(twc.size() > 0) {
                        
            Tilewall_Config__c c = twc[0];
                        
            Set<String> fieldNamesSet = new Set<String>();
            List<String> fieldNamesList = new List<String>();
                        
            Map<String,Object> base = new Map<String,Object>();
            for(String fieldName : baseFields) {
                if(twc[0].get(fieldName) != null && twc[0].get(fieldName) != '') {
                    String prop = fieldName.removeEnd('__c');
                    base.put(prop, twc[0].get(fieldName));
                }
            }
            TileWallConfig config = (TileWallConfig)JSON.deserialize(JSON.serialize(base),TileWallConfig.class);
            
            config.titleClasses = 'tile-title-value slds-item_detail';
            if(! String.isBlank(config.titleSize)) {
                config.titleClasses += ' slds-text-'+config.titleSize;
                config.hasTitleSize = true;
            }
            if(! String.isBlank(config.titleTextCase)) {
                config.hasTitleTextCase = true;
            }
            if(! String.isBlank(config.titleAlign)) {
                config.titleClasses += ' slds-text-align_'+config.titleAlign;
                config.hasTitleAlign = true;
            }
            if(! String.isBlank(config.showMedia)) {
                if(config.showMedia == 'image') {
                	config.imageClasses = 'slds-avatar';
                	if(! String.isBlank(config.mediaSize)) config.imageClasses += ' slds-avatar_' + config.mediaSize;
					if(! String.isBlank(config.mediaFormat) && config.mediaFormat == 'circle') config.imageClasses += ' slds-avatar_circle';
                }
            }
            if(! fieldNamesSet.contains(config.titleName.toLowerCase())) {
                fieldNamesSet.add(config.titleName.toLowerCase());
                fieldNamesList.add(config.titleName);
            }
                        
            config.sizeLarge = 12/config.columnsLarge;
            config.sizeMedium = 12/config.columnsMedium;
            config.sizeSmall = 12/config.columnsSmall;
            
            if(! config.useAdvancedOrdering) {
                if(! String.isBlank(config.orderByFieldname)) {
                    config.orderBy = config.orderByFieldname;
                    config.orderBy += (! String.isBlank(config.orderByDirection)) ? ' '+config.orderByDirection : ' ASC';
                } else {
                    config.orderBy = '';
                }
            }
            
            if(! String.isBlank(config.mediaFieldname)) {
                config.hasMediaField = true;
                if(! fieldNamesSet.contains(config.mediaFieldname.toLowerCase())) {
                    fieldNamesSet.add(config.mediaFieldname.toLowerCase());
                    fieldNamesList.add(config.mediaFieldname);
                }
            }
            if(! String.isBlank(config.imageFieldName)) {
                config.hasImageField = true;
                if(! fieldNamesSet.contains(config.imageFieldName.toLowerCase())) {
                    fieldNamesSet.add(config.imageFieldName.toLowerCase());
                    fieldNamesList.add(config.imageFieldName);
                }
            }
            if(! String.isBlank(config.imageURL)) config.hasImageURL = true;
            if(! String.isBlank(config.colorFieldName)) {
                config.hasColorField = true;
                if(! fieldNamesSet.contains(config.colorFieldName.toLowerCase())) {
                    fieldNamesSet.add(config.colorFieldName.toLowerCase());
                    fieldNamesList.add(config.colorFieldName);
                }
            }
            if(! String.isBlank(config.media)) config.hasMedia = true;
            if(! String.isBlank(config.color)) config.hasColor = true;
            if(! String.isBlank(config.opacity)) config.hasOpacity = true;
            if(! String.isBlank(config.size)) config.hasSize = true;
            if(! String.isBlank(config.heightOption)) config.hasHeightOption = true;
            if(! String.isBlank(config.fixedHeight)) config.hasFixedHeight = true;
            
            if(! String.isBlank(config.fieldStyle) && config.fieldStyle == 'horizontal') {
                config.fieldClasses = 'slds-table slds-table_header-hidden slds-no-row-hover tilewall-table';
                config.isHorizontal = true;
                config.isStacked = false;
            } else {
                config.fieldClasses = 'slds-list_stacked';
                config.isStacked = true;
                config.isHorizontal = false;
            }
            
            String valuePadding = '';
            String labelPadding = '';
            if(! config.padding) {
                valuePadding = ' slds-p-left_none slds-p-right_none';
                labelPadding = ' slds-p-left_none';
            } else if(config.isStacked) {
                valuePadding = ' slds-p-left_x-small slds-p-right_x-small';
                labelPadding = ' slds-p-left_x-small slds-p-right_x-small';
            }

            
            
            List<Tilewall_Field__c> twf = [SELECT Id, Name, type__c, apiName__c, label__c, order__c, size__c, textCase__c, align__c, color__c, colorFieldname__c, bgColor__c, bgColorFieldname__c, labelColor__c, labelColorFieldname__c, labelBgColor__c, labelBgColorFieldname__c, badgeIcon__c, badgeIconFieldname__c, flow__c, showActionFieldname__c, actionVar1__c, actionVar2__c, actionVar3__c
                                           FROM Tilewall_Field__c 
                                           WHERE Config_Id__c=:c.Id
                                           ORDER BY order__c ASC];

            
           	if(twf.size() > 0) {
            
                List<TilewallField> fields = new List<TilewallField>();
                List<TilewallBadge> badges = new List<TilewallBadge>();
                List<TilewallAction> actions = new List<TilewallAction>();
                
                for(Tilewall_Field__c field : twf) {

                    if(! String.isBlank(field.apiName__c) && field.type__c == 'Field') {
                            
                        TilewallField f = new TilewallField();
                        f.name = field.apiName__c;
                        if(! fieldNamesSet.contains(f.name.toLowerCase())) {
                            fieldNamesSet.add(f.name.toLowerCase());
                            fieldNamesList.add(f.name);
                        }
                        f.num = fields.size()+1;
                        f.valueClasses = 'tile-field' + f.num + '-value tile-field-value' + valuePadding;
                        if(config.isStacked) f.valueClasses += ' slds-item_detail';
                        if(config.isHorizontal) f.valueClasses += ' slds-cell-wrap vertical-align-top slds-p-vertical_none';
                        if(! String.isBlank(field.label__c)) {
                           	f.label = field.label__c;
                            f.labelClasses = 'tile-field' + f.num + '-label tile-field-label slds-text-color_weak' + labelPadding;
                            if(config.isStacked) f.labelClasses += ' slds-item_label slds-truncate';
                            if(config.isHorizontal) f.labelClasses += ' slds-cell-wrap vertical-align-top slds-p-vertical_none';
                            f.hasLabel = true;
                        }
                        if(! String.isBlank(field.size__c)) {
                            f.size = field.size__c;
                            f.valueClasses += ' slds-text-'+f.size;
                            f.hasSize = true;
                        }
                        if(! String.isBlank(field.textCase__c)) {
                            f.textCase = field.textCase__c;
                            f.hasTextCase = true;
                        }
                        if(! String.isBlank(field.align__c)) {
                            f.align = field.align__c;
                            f.valueClasses += ' slds-text-align_'+f.align;
                            f.hasAlign = true;
                        }
                            
                        if(! String.isBlank(field.color__c)) {
                            f.color = field.color__c;
                            f.hasColor = true;
                        }
                        if(! String.isBlank(field.colorFieldname__c)) {
                            f.colorFieldname = field.colorFieldname__c;
                            f.hasColorFieldname = true;
                            if(! fieldNamesSet.contains(f.colorFieldname.toLowerCase())) {
                                fieldNamesSet.add(f.colorFieldname.toLowerCase());
                                fieldNamesList.add(f.colorFieldname);
                            }
                        }
                        if(! String.isBlank(field.bgColor__c)) {
                            f.bgColor = field.bgColor__c;
                            f.hasBGColor = true;
                        }
                        if(! String.isBlank(field.bgColorFieldname__c)) {
                            f.bgColorFieldname = field.bgColorFieldname__c;
                            f.hasBGColorFieldname = true;
                            if(! fieldNamesSet.contains(f.bgColorFieldname.toLowerCase())) {
                                fieldNamesSet.add(f.bgColorFieldname.toLowerCase());
                                fieldNamesList.add(f.bgColorFieldname);
                            }
                        }

                        if(! String.isBlank(field.labelColor__c)) {
                            f.labelColor = field.labelColor__c;
                            f.hasLabelColor = true;
                        }
                        if(! String.isBlank(field.labelColorFieldname__c)) {
                            f.labelColorFieldname = field.labelColorFieldname__c;
                            f.hasLabelColorFieldname = true;
                            if(! fieldNamesSet.contains(f.labelColorFieldname.toLowerCase())) {
                                fieldNamesSet.add(f.labelColorFieldname.toLowerCase());
                                fieldNamesList.add(f.labelColorFieldname);
                            }
                        }
                        if(! String.isBlank(field.labelBgColor__c)) {
                            f.labelBgColor = field.labelBgColor__c;
                            f.hasLabelBgColor = true;
                        }
                        if(! String.isBlank(field.labelBgColorFieldname__c)) {
                            f.labelBgColorFieldname = field.labelBgColorFieldname__c;
                            f.hasLabelBgColorFieldname = true;
                            if(! fieldNamesSet.contains(f.labelBgColorFieldname.toLowerCase())) {
                                fieldNamesSet.add(f.labelBgColorFieldname.toLowerCase());
                                fieldNamesList.add(f.labelBgColorFieldname);
                            }
                        }
                        fields.add(f);
                        
                    } else if(! String.isBlank(field.apiName__c) && field.type__c == 'Badge') {
                        
                        TilewallBadge b = new TilewallBadge();
                        b.name = field.apiName__c;
                        if(! fieldNamesSet.contains(b.name.toLowerCase())) {
                            fieldNamesSet.add(b.name.toLowerCase());
                            fieldNamesList.add(b.name);
                        }
                        b.num = badges.size()+1;
                        b.badgeClasses = ' tile-badge'+b.num+' tile-badge slds-badge slds-m-bottom_none slds-m-left_none slds-m-right_x-small slds-truncate';
                        if(! String.isBlank(field.label__c)) {
                            b.label = field.label__c;
                            b.labelClasses = 'tile-badge'+b.num+'-label tile-badge-label';
                            b.hasLabel = true;
                        }
                        b.valueClasses = 'tile-badge'+b.num+'-value tile-badge-value';
                        if(! String.isBlank(field.textCase__c)) {
                            b.textCase = field.textCase__c;
                            b.hasTextCase = true;
                        }
                        if(! String.isBlank(field.badgeIcon__c)) {
                            b.badgeIcon = field.badgeIcon__c;
                            b.hasBadgeIcon = true;
                        }
                        if(! String.isBlank(field.badgeIconFieldname__c)) {
                            b.badgeIconFieldname = field.badgeIconFieldname__c;
                            b.hasBadgeIconFieldname = true;
                            if(! fieldNamesSet.contains(b.badgeIconFieldname.toLowerCase())) {
                                fieldNamesSet.add(b.badgeIconFieldname.toLowerCase());
                                fieldNamesList.add(b.badgeIconFieldname);
                            }
                        }
                        if(! String.isBlank(field.color__c)) {
                            b.color = field.color__c;
                            b.hasColor = true;
                        }
                        if(! String.isBlank(field.colorFieldname__c)) {
                            b.colorFieldname = field.colorFieldname__c;
                            b.hasColorFieldname = true;
                            if(! fieldNamesSet.contains(b.colorFieldname.toLowerCase())) {
                                fieldNamesSet.add(b.colorFieldname.toLowerCase());
                                fieldNamesList.add(b.colorFieldname);
                            }
                        }
                        if(! String.isBlank(field.bgColor__c)) {
                            b.bgColor = field.bgColor__c;
                            b.hasBGColor = true;
                        }
                        if(! String.isBlank(field.bgColorFieldname__c)) {
                            b.bgColorFieldname = field.bgColorFieldname__c;
                            b.hasBGColorFieldname = true;
                            if(! fieldNamesSet.contains(b.bgColorFieldname.toLowerCase())) {
                                fieldNamesSet.add(b.bgColorFieldname.toLowerCase());
                                fieldNamesList.add(b.bgColorFieldname);
                            }
                        }
                        badges.add(b);   

                    } else if(field.type__c == 'action') {
                            
                        TilewallAction a = new TilewallAction();
                        a.name = field.flow__c;
                        a.num = actions.size()+1;
                        a.flow = field.flow__c;
                        a.label = (! String.isBlank(field.label__c)) ? field.label__c : field.flow__c;
                        if(! String.isBlank(field.showActionFieldname__c)) {
                            a.showActionFieldname = field.showActionFieldname__c;
                            a.hasShowActionFieldname = true;
                            if(! fieldNamesSet.contains(a.showActionFieldname.toLowerCase())) {
                            	fieldNamesSet.add(a.showActionFieldname.toLowerCase());
                            	fieldNamesList.add(a.showActionFieldname);
                        	}
                        }
                        if(! String.isBlank(field.actionVar1__c)) a.actionVar1 = field.actionVar1__c;
                        if(! String.isBlank(field.actionVar2__c)) a.actionVar2 = field.actionVar2__c;
                        if(! String.isBlank(field.actionVar3__c)) a.actionVar3 = field.actionVar3__c;
                        actions.add(a);

                    }
                    
                }
                
                if(fields.size() > 0) config.fields = fields;
                if(badges.size() > 0) config.badges = badges;
                if(actions.size() > 0) config.actions = actions;
	        }
         
            config.fieldNames = fieldNamesList;
            return JSON.serialize(config, true);
            
        }

		return null;        
    } 

    
    public class TileWallConfig {
        public String title;
        public String iconName;
        public String iconSize;
        public Boolean displayCount;
        public Integer limitResults;
        public String orderBy;
        public String orderByFieldname;
        public String orderByDirection;
        public Boolean useAdvancedOrdering;
        public Boolean allowSearch;
        public String searchLabel;
        public String noResultsText;
        public Integer columnsLarge;
        public Integer columnsMedium;
        public Integer columnsSmall;
        public Integer sizeLarge;
        public Integer sizeMedium;
        public Integer sizeSmall;
        public String backgroundColor;
        public Boolean hasBackgroundColor;
        public String color;
        public Boolean hasColor;
        public String colorFieldName;
        public Boolean hasColorField;
        public String imageURL;
        public Boolean hasImageURL;
        public String imageFieldName;
        public Boolean hasImageField;
        public String opacity;
        public Boolean hasOpacity;
        public String size;
        public Boolean hasSize;
        public String heightOption;
        public Boolean hasHeightOption;
        public String fixedHeight;
		public Boolean hasFixedHeight;  
        public String titleName;
        public String titleSize;
        public Boolean hasTitleSize;
        public String titleTextCase;
        public Boolean hasTitleTextCase;
        public String titleAlign;
        public Boolean hasTitleAlign;
        public String titleClasses;
        public String fieldStyle;
        public Boolean padding;
        public String fieldClasses;
        public Boolean isHorizontal;
        public Boolean isStacked;
        public String showMedia;
        public String media;
        public Boolean hasMedia;
        public String mediaFieldname;
        public Boolean hasMediaField;
        public String mediaFormat;
        public String mediaSize;
        public String imageClasses;
		public List<TileWallField> fields;
        public List<TileWallBadge> badges;
        public List<TileWallAction> actions;
        
        public List<String> fieldNames;
    }
    
    
    public class TileWallField {
        public Integer num;
		public String name;
        public String label;
        public Boolean hasLabel;
        public String labelClasses;
        public String textCase;
        public Boolean hasTextCase;
        public String align;
        public Boolean hasAlign;
        public String size;
        public Boolean hasSize;
        public String color;
        public Boolean hasColor;
        public String colorFieldname;
        public Boolean hasColorFieldname;
        public String bgColor;
        public Boolean hasBgColor;
        public String bgColorFieldname;
        public Boolean hasBgColorFieldname;
        public String labelColor;
        public Boolean hasLabelColor;
        public String labelColorFieldname;
        public Boolean hasLabelColorFieldname;
        public String labelBgColor;
        public Boolean hasLabelBgColor;
        public String labelBgColorFieldname;
        public Boolean hasLabelBgColorFieldname;

        public String valueClasses;
    }
    
    public class TileWallBadge {
        public Integer num;
        public String name;
        public String label;
        public Boolean hasLabel;
        public String badgeClasses;
        public String labelClasses;
        public String textCase;
        public Boolean hasTextCase;
        public String color;
        public Boolean hasColor;
        public String colorFieldname;
        public Boolean hasColorFieldname;
        public String bgColor;
        public Boolean hasBgColor;
        public String bgColorFieldname;
        public Boolean hasBgColorFieldname;
        public String badgeIcon;
        public Boolean hasBadgeIcon;
        public String badgeIconFieldname;
        public Boolean hasBadgeIconFieldname;
        public String valueClasses;
    }   
    
    public class TileWallAction {
        public Integer num;
        public String name;
        public String label;
        public Boolean hasLabel;
        public String flow;
        public String showActionFieldname;
        public Boolean hasShowActionFieldname;
		public String actionVar1;
		public String actionVar2;
		public String actionVar3;        
    }
        
}