force-app/main/default/objects/Dynacat_Product__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <label>Background Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dynacat_Product__c/fields/Background_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Background_Image_URL__c</fullName>
    <label>Background Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/Tilewall_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Tilewall Config</label>
</CustomObject>

force-app/main/default/objects/Tilewall_Config__c/fields/allowSearch__c.field-meta.xml
<CustomField>
    <fullName>allowSearch__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Adds a search box to the header of the component to enable free-text search of the records. Uses SOSL search which searches most fields, including those not displayed in the tile.</inlineHelpText>
    <label>Allow Search</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/backgroundColor__c.field-meta.xml
<CustomField>
    <fullName>backgroundColor__c</fullName>
    <defaultValue>&apos;#FFFFFF&apos;</defaultValue>
    <inlineHelpText>Background color for the overall Tile Wall component</inlineHelpText>
    <label>Tile Wall Background Color</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/color__c.field-meta.xml
<CustomField>
    <fullName>color__c</fullName>
    <defaultValue>&apos;#FFFFFF&apos;</defaultValue>
    <inlineHelpText>Background color for each individual tile.  6-character HEX format (eg #FFFFFF) MUST be used if opacity is specified.</inlineHelpText>
    <label>Tile Background Color</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/colorFieldName__c.field-meta.xml
<CustomField>
    <fullName>colorFieldName__c</fullName>
    <inlineHelpText>API Name of a record field that provides the background color for the tile, eg. through a formula.  6-char HEX format (eg #FFFFFF) MUST be used by this field if opacity is specified.</inlineHelpText>
    <label>Tile Background Color Fieldname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/columnsLarge__c.field-meta.xml
<CustomField>
    <fullName>columnsLarge__c</fullName>
    <defaultValue>4</defaultValue>
    <label>Tiles per Row (Desktop)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/columnsMedium__c.field-meta.xml
<CustomField>
    <fullName>columnsMedium__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Tiles per Row (Tablet)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/columnsSmall__c.field-meta.xml
<CustomField>
    <fullName>columnsSmall__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Tiles per Row (Mobile)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/displayCount__c.field-meta.xml
<CustomField>
    <fullName>displayCount__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Display the record count in brackets in the component header.</inlineHelpText>
    <label>Display Record Count</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/fieldStyle__c.field-meta.xml
<CustomField>
    <fullName>fieldStyle__c</fullName>
    <defaultValue>&apos;horizontal&apos;</defaultValue>
    <inlineHelpText>Options: horizontal,stacked</inlineHelpText>
    <label>Field Style</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/fixedHeight__c.field-meta.xml
<CustomField>
    <fullName>fixedHeight__c</fullName>
    <inlineHelpText>Fixed Height in pixels (px) or percent (%).  Enter the number and the unit - eg 200px or 10%</inlineHelpText>
    <label>Fixed Height</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/heightOption__c.field-meta.xml
<CustomField>
    <fullName>heightOption__c</fullName>
    <defaultValue>&apos;max-row&apos;</defaultValue>
    <inlineHelpText>Options: max-row,fixed,individual.  Max-Row: Tile auto-size height to fit contents, each tile in a row will be the same height; Fixed: Fixed at specified height; Individual: Each tile sized to fit content.</inlineHelpText>
    <label>Tile Height</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/iconName__c.field-meta.xml
<CustomField>
    <fullName>iconName__c</fullName>
    <inlineHelpText>(Optional) Enter the icon name to appear in the header, eg. standard:account or utility:event. Google &apos;slds icons&apos; to see them all.</inlineHelpText>
    <label>Icon Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/imageFieldName__c.field-meta.xml
<CustomField>
    <fullName>imageFieldName__c</fullName>
    <inlineHelpText>API Name of a record field that provides the URL for that tile&apos;s background, eg. through a formula field. Make sure the site hosting the image is added to CSP Trusted Sites if this component is used in Experience Cloud.</inlineHelpText>
    <label>Tile Background Image Fieldname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/imageURL__c.field-meta.xml
<CustomField>
    <fullName>imageURL__c</fullName>
    <inlineHelpText>URL for a default image to be used as each tile&apos;s background. If the Tile Wall is being displayed in Experience Cloud, make sure the site hosting the image is included as a CSP trusted site.</inlineHelpText>
    <label>Tile Background Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/limitResults__c.field-meta.xml
<CustomField>
    <fullName>limitResults__c</fullName>
    <defaultValue>12</defaultValue>
    <inlineHelpText>Controls how many records will be displayed on each page</inlineHelpText>
    <label>Limit Displayed Records</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/noResultsText__c.field-meta.xml
<CustomField>
    <fullName>noResultsText__c</fullName>
    <defaultValue>&apos;No results found, try searching for something else.&apos;</defaultValue>
    <inlineHelpText>Text to display if no results are found after searching</inlineHelpText>
    <label>No Search Results Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/opacity__c.field-meta.xml
<CustomField>
    <fullName>opacity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Opacity of the tiles between 0.0 ((fully transparent) and 1.0 opaque). 6-char HEX color values (eg. #FFFFFF) must be used if opacity is set. Opacity doesn&apos;t work on iOS, tiles will fallback to default background color (no background image).</inlineHelpText>
    <label>Tile Background Opacity</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/orderBy__c.field-meta.xml
<CustomField>
    <fullName>orderBy__c</fullName>
    <inlineHelpText>Use SOQL Syntax for advanced ordering eg. &apos;Name ASC, CloseDate DESC&apos;</inlineHelpText>
    <label>Order By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/orderByDirection__c.field-meta.xml
<CustomField>
    <fullName>orderByDirection__c</fullName>
    <defaultValue>&apos;ASC&apos;</defaultValue>
    <inlineHelpText>ASC, DESC</inlineHelpText>
    <label>Order By Direction</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/orderByFieldname__c.field-meta.xml
<CustomField>
    <fullName>orderByFieldname__c</fullName>
    <label>Order By Fieldname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/padding__c.field-meta.xml
<CustomField>
    <fullName>padding__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Applies padding to the left and right of each field and label.  In horizontal mode, a small amount of padding will be applied to the right of the label if unchecked, to enable separation.</inlineHelpText>
    <label>Field Padding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/searchLabel__c.field-meta.xml
<CustomField>
    <fullName>searchLabel__c</fullName>
    <defaultValue>&apos;Search&apos;</defaultValue>
    <inlineHelpText>Label for the search box, if displayed.</inlineHelpText>
    <label>Search Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/showMedia__c.field-meta.xml
<CustomField>
    <fullName>showMedia__c</fullName>
    <inlineHelpText>Options: icon, image, none</inlineHelpText>
    <label>Show Media</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/size__c.field-meta.xml
<CustomField>
    <fullName>size__c</fullName>
    <defaultValue>&apos;cover&apos;</defaultValue>
    <inlineHelpText>Google &apos;css background-size&apos; for details of each option. Options: auto,length,cover,contain,initial,inherit.</inlineHelpText>
    <label>Tile Background Image Size</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <inlineHelpText>Title for the header of the tile wall component (as opposed to an individual tile)</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/titleAlign__c.field-meta.xml
<CustomField>
    <fullName>titleAlign__c</fullName>
    <defaultValue>&apos;left&apos;</defaultValue>
    <inlineHelpText>Title Alignment. Options: left,center,right</inlineHelpText>
    <label>Title Alignment</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/titleName__c.field-meta.xml
<CustomField>
    <fullName>titleName__c</fullName>
    <label>Title API Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/titleSize__c.field-meta.xml
<CustomField>
    <fullName>titleSize__c</fullName>
    <defaultValue>&apos;body_regular&apos;</defaultValue>
    <inlineHelpText>Text size style for the title (google &apos;slds text&apos; for examples of each style). Options: body_regular,body_small,heading_large,heading_medium,heading_small</inlineHelpText>
    <label>Title Size</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/titleTextCase__c.field-meta.xml
<CustomField>
    <fullName>titleTextCase__c</fullName>
    <defaultValue>&apos;default&apos;</defaultValue>
    <inlineHelpText>Title Case Display. Options: default,lowercase,uppercase</inlineHelpText>
    <label>Title Text Case</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Config__c/fields/useAdvancedOrdering__c.field-meta.xml
<CustomField>
    <fullName>useAdvancedOrdering__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Advanced Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/Tilewall_Field__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Tilewall Field</label>
</CustomObject>

force-app/main/default/objects/Tilewall_Field__c/fields/align__c.field-meta.xml
<CustomField>
    <fullName>align__c</fullName>
    <defaultValue>&apos;left&apos;</defaultValue>
    <inlineHelpText>Field Alignment. Options: left,center,right</inlineHelpText>
    <label>Alignment</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/fields/color__c.field-meta.xml
<CustomField>
    <fullName>color__c</fullName>
    <label>Text Color</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/fields/colorFieldname__c.field-meta.xml
<CustomField>
    <fullName>colorFieldname__c</fullName>
    <label>Text Color Fieldname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/fields/label__c.field-meta.xml
<CustomField>
    <fullName>label__c</fullName>
    <inlineHelpText>Optional label for this field.  If omitted, the value will take up the full space.</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/fields/size__c.field-meta.xml
<CustomField>
    <fullName>size__c</fullName>
    <defaultValue>&apos;body_regular&apos;</defaultValue>
    <inlineHelpText>Text size style (google &apos;slds text&apos; for examples of each style). Options: body_regular,body_small,heading_large,heading_medium,heading_small</inlineHelpText>
    <label>Size</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tilewall_Field__c/fields/textCase__c.field-meta.xml
<CustomField>
    <fullName>textCase__c</fullName>
    <defaultValue>&apos;default&apos;</defaultValue>
    <inlineHelpText>Options:default,uppercase,lowercase</inlineHelpText>
    <label>Text Case</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TilewallTests_Dynacat.cls
@isTest
public class TilewallTests_Dynacat {

    @testsetup static void setupTestData() {
        
    	// Create some Tilewall config records
    	
        Tilewall_Config__c tc = new Tilewall_Config__c(	Name='Test Config', 
                                                        Summary__c='Test Tilewall Config', 
                                                        Object_API_Name__c='Dynacat_Product__c',
                                                        title__c='Test Tilewall',
                										iconName__c='standard:account', 
                										displayCount__c=true, 
                										allowSearch__c=true, 
                										searchLabel__c='Search Test', 
                										noResultsText__c='No results', 
                										orderBy__c='Name ASC',
                										orderByFieldname__c='Name',
                										orderByDirection__c='ASC',
                										useAdvancedOrdering__c=false,
                										limitResults__c=12, 
                										columnsLarge__c=4, 
                										columnsMedium__c=3, 
                										columnsSmall__c=1, 
                										backgroundColor__c='#FFFFFF', 
                										color__c='#FFFFFF', 
                										colorFieldName__c='Background_Color__c', 
                										imageURL__c='https://www.test.com', 
                										imageFieldName__c='Background_Image_URL__c', 
                										opacity__c=1.0, 
                										size__c='cover', 
                										heightOption__c='max-row', 
                										fixedHeight__c='',
                										titleName__c='Name',
                										titleSize__c='body_regular',
                										titleTextCase__c='uppercase',
                										titleAlign__c='center',
                										fieldStyle__c='horizontal',
                										padding__c=false,
                										showMedia__c='icon',
                										media__c='standard:product',
                										mediaFieldname__c='Tile_Image_URL__c',
                										mediaFormat__c='circle',
                										mediaSize__c='medium'
                                                      );
        insert(tc);
        
        Tilewall_Config__c tc2 = tc.clone();
        tc2.Name = 'Test Config2';
        tc2.showMedia__c = 'image';
        tc2.orderByFieldname__c = '';
        tc2.fieldStyle__c = 'stacked';
        tc2.padding__c = true;
        insert(tc2);
        
        Tilewall_Field__c tf1 = new Tilewall_Field__c( Name='Test Field',
                                                       Config_Id__c = tc.Id,
                                                       type__c = 'field',
                                                       apiName__c = 'Status__c', 
                                                       label__c = 'Status',
                                                       order__c = 10, 
                                                       size__c = 'body_regular', 
                                                       textCase__c = 'lowercase',
                                                       align__c = 'right', 
                                                       color__c = '#333333', 
                                                       colorFieldname__c = 'Field_Text_Color__c',
                                                       bgColor__c = '#FFFFFF', 
                                                       bgColorFieldname__c = 'Field_Background_Color__c', 
                                                       labelColor__c = '#CCCCCC', 
                                                       labelColorFieldname__c = 'Label_Text_Color__c', 
                                                       labelBgColor__c = '#FFFFFF', 
                                                       labelBgColorFieldname__c = 'Label_Background_Color__c');
        insert(tf1);
        
        Tilewall_Field__c tf2 = tf1.clone();
        tf2.Name = 'Test Badge1';
        tf2.type__c = 'badge';
        tf2.apiName__c = 'Vendor__r.Name';
        tf2.order__c = 20;
        tf2.textCase__c = 'default';
        tf2.badgeIcon__c = 'utility:watchlist';
        tf2.badgeIconFieldname__c = 'Badge_Icon_Name__c';
        insert(tf2);
        
        Tilewall_Field__c tf3 = new Tilewall_Field__c();
        tf3.Config_Id__c = tc.Id;
        tf3.Name = 'Test Action1';
        tf3.type__c = 'action';
        tf3.order__c = 10;
        tf3.flow__c = 'Test_Flow';
        tf3.showActionFieldname__c = 'Recommended__c';
        tf3.actionVar1__c = 'Var1';
        tf3.actionVar2__c = 'Var2';
        tf3.actionVar3__c = 'Var3';
        insert(tf3);
        
    }
    
    @isTest static void TilewallController_GetTilewallConfig() {
        
        Test.startTest();        
        String config1 = TilewallController_Dynacat.getTileWallConfig('Test Config');
        TilewallController_Dynacat.TileWallConfig resp1 = (TilewallController_Dynacat.TileWallConfig)JSON.deserialize(config1, TilewallController_Dynacat.TileWallConfig.class);
        String config2 = TilewallController_Dynacat.getTileWallConfig('Test Config2');
        TilewallController_Dynacat.TileWallConfig resp2 = (TilewallController_Dynacat.TileWallConfig)JSON.deserialize(config2, TilewallController_Dynacat.TileWallConfig.class);
        Test.stopTest();

        System.assertEquals('stacked', resp2.fieldStyle);
        
        System.debug('Tilewall Config1: '+config1); 
        System.debug('Tilewall Config2: '+config2);   

    }
    
    @isTest static void Tilewall_PicklistConfigs() {
        Test.startTest();
        
        Tilewall_Picklist_Configs configs = new Tilewall_Picklist_Configs();
        VisualEditor.DynamicPicklistRows configRows = configs.getValues();
        VisualEditor.DataRow configDefault = configs.getDefaultValue();
        
        Test.stopTest();
    }
}